/** @type {import('tailwindcss').Config} */
export default {
  darkMode: 'class',
  content: [
    "./index.html",
    "./src/**/*.{js,ts,jsx,tsx}",
  ],
  theme: {
    extend: {
      colors: {
        /* === 小红书品牌色 (红色为核心) === */
        'brand-1': '#FFF0F2',
        'brand-2': '#FFD6DC',
        'brand-3': '#FFB3C0',
        'brand-4': '#FF8FA3',
        'brand-5': '#FF2442',
        'brand-6': '#E01E3C',
        'brand-7': '#C41835',
        'brand-8': '#A3132D',
        'brand-9': '#800F24',

        /* === 小红书暖灰系统 === */
        'gray-1': '#FBFBFB',
        'gray-2': '#F5F5F5',
        'gray-3': '#E8E8E8',
        'gray-4': '#D9D9D9',
        'gray-5': '#BFBFBF',
        'gray-6': '#8C8C8C',
        'gray-7': '#595959',
        'gray-8': '#434343',
        'gray-9': '#262626',
        'gray-10': '#141414',
        'gray-11': '#000000',

        /* === 语义色 === */
        'success-1': '#F6FFED',
        'success-5': '#52C41A',
        'warning-1': '#FFFBE6',
        'warning-5': '#FAAD14',
        'error-1': '#FFF2F0',
        'error-5': '#FF4D4F',
        'info-1': '#E6F7FF',
        'info-5': '#1890FF',

        /* === CSS变量映射 === */
        'bg-page': 'var(--bg-page)',
        'bg-container': 'var(--bg-container)',
        'bg-elevated': 'var(--bg-elevated)',
        'bg-component': 'var(--bg-component)',
        'bg-sidebar': 'var(--bg-sidebar)',
        'text-primary': 'var(--text-primary)',
        'text-secondary': 'var(--text-secondary)',
        'text-tertiary': 'var(--text-tertiary)',
        'text-placeholder': 'var(--text-placeholder)',
        'text-link': 'var(--text-link)',
        'border-1': 'var(--border-1)',
        'border-2': 'var(--border-2)',
        'border-3': 'var(--border-3)',
        'border-focus': 'var(--border-focus)',

        /* === 角色色彩 (小红书风格) === */
        'role-host': '#FF2442',
        'role-proposer': '#FF6B8A',
        'role-reviewer': '#FAAD14',
        'role-system': '#8C8C8C',
      },
      fontFamily: {
        sans: [
          '-apple-system',
          'BlinkMacSystemFont',
          'Segoe UI',
          'PingFang SC',
          'Hiragino Sans GB',
          'Microsoft YaHei',
          'Helvetica Neue',
          'Helvetica',
          'Arial',
          'sans-serif',
        ],
        mono: ['JetBrains Mono', 'Fira Code', 'monospace'],
      },
      borderRadius: {
        'small': '6px',
        'medium': '12px',
        'large': '16px',
        'extra': '20px',
        'round': '999px',
      },
      boxShadow: {
        '1': '0 2px 8px rgba(0, 0, 0, 0.06)',
        '2': '0 4px 12px rgba(0, 0, 0, 0.08)',
        '3': '0 6px 16px rgba(0, 0, 0, 0.1)',
        '4': '0 8px 24px rgba(0, 0, 0, 0.12)',
        '5': '0 12px 32px rgba(0, 0, 0, 0.15)',
      },
      spacing: {
        '1': '4px',
        '2': '8px',
        '3': '12px',
        '4': '16px',
        '5': '20px',
        '6': '24px',
        '8': '32px',
        '10': '40px',
        '12': '48px',
      },
      fontSize: {
        'h1': ['28px', { lineHeight: '1.4', fontWeight: '700' }],
        'h2': ['22px', { lineHeight: '1.4', fontWeight: '600' }],
        'h3': ['18px', { lineHeight: '1.4', fontWeight: '600' }],
        'h4': ['16px', { lineHeight: '1.4', fontWeight: '600' }],
        'body': ['14px', { lineHeight: '1.5', fontWeight: '400' }],
        'small': ['13px', { lineHeight: '1.5', fontWeight: '400' }],
        'extra': ['12px', { lineHeight: '1.5', fontWeight: '400' }],
      },
      transitionDuration: {
        'fast': '150ms',
        'normal': '250ms',
        'slow': '350ms',
      },
      transitionTimingFunction: {
        'ease': 'cubic-bezier(0.4, 0, 0.2, 1)',
        'bounce': 'cubic-bezier(0.34, 1.56, 0.64, 1)',
      },
    },
  },
  plugins: [
    require('@tailwindcss/line-clamp'),
  ],
}
